// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace DeberPrograPao1ML.Model
{
    public class ModelInput
    {
        [ColumnName("Id"), LoadColumn(0)]
        public string Id { get; set; }


        [ColumnName("UserName"), LoadColumn(1)]
        public string UserName { get; set; }


        [ColumnName("NormalizedUserName"), LoadColumn(2)]
        public string NormalizedUserName { get; set; }


        [ColumnName("Email"), LoadColumn(3)]
        public string Email { get; set; }


        [ColumnName("NormalizedEmail"), LoadColumn(4)]
        public string NormalizedEmail { get; set; }


        [ColumnName("EmailConfirmed"), LoadColumn(5)]
        public bool EmailConfirmed { get; set; }


        [ColumnName("PasswordHash"), LoadColumn(6)]
        public string PasswordHash { get; set; }


        [ColumnName("SecurityStamp"), LoadColumn(7)]
        public string SecurityStamp { get; set; }


        [ColumnName("ConcurrencyStamp"), LoadColumn(8)]
        public string ConcurrencyStamp { get; set; }


        [ColumnName("PhoneNumber"), LoadColumn(9)]
        public float PhoneNumber { get; set; }


        [ColumnName("PhoneNumberConfirmed"), LoadColumn(10)]
        public bool PhoneNumberConfirmed { get; set; }


        [ColumnName("TwoFactorEnabled"), LoadColumn(11)]
        public bool TwoFactorEnabled { get; set; }


        [ColumnName("LockoutEnd"), LoadColumn(12)]
        public float LockoutEnd { get; set; }


        [ColumnName("LockoutEnabled"), LoadColumn(13)]
        public bool LockoutEnabled { get; set; }


        [ColumnName("AccessFailedCount"), LoadColumn(14)]
        public float AccessFailedCount { get; set; }


    }
}
